version: "3.8"

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.32
    restart: always
    ports:
      - "3307:3306"
    networks:
      - shop_net
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USER=${MYSQL_USERNAME}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "TZ=${TIMEZONE}"

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - "8001:80"
    networks:
      - shop_net
    links:
      - mysql:db
    environment:
      - "TZ=${TIMEZONE}"

  backend:
    container_name: backend
    build: .
    image: shop-backend:v1
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:8080"
    networks:
      - shop_net
    volumes:
      - upload_dir:${UPLOAD_DIR}
    environment:
      - "MYSQL_HOST=${MYSQL_HOST}"
      - "MYSQL_PORT=${MYSQL_PORT}"
      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
      - "MYSQL_USERNAME=${MYSQL_USERNAME}"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
      - "MAIL_HOST=${MAIL_HOST}"
      - "MAIL_PORT=${MAIL_PORT}"
      - "MAIL_USERNAME=${MAIL_USERNAME}"
      - "MAIL_PASSWORD=${MAIL_PASSWORD}"
      - "API_DOCS_ENABLED=${API_DOCS_ENABLED}"
      - "MAIL_SENDER_ADDRESS=${MAIL_SENDER_ADDRESS}"
      - "MAIL_FAKE_SERVICE_ENABLED=${MAIL_FAKE_SERVICE_ENABLED}"
      - "P24_TEST_MODE=${P24_TEST_MODE}"
      - "P24_MERCHANT_ID=${P24_MERCHANT_ID}"
      - "P24_POS_ID=${P24_POS_ID}"
      - "P24_CRC=${P24_CRC}"
      - "P24_TEST_CRC=${P24_TEST_CRC}"
      - "P24_SECRET_ID=${P24_SECRET_ID}"
      - "P24_TEST_SECRET_ID=${P24_TEST_SECRET_ID}"
      - "P24_URL_RETURN=${P24_URL_RETURN}"
      - "P24_URL_STATUS=${P24_URL_STATUS}"
      - "FRONTEND_ADDRESS=${FRONTEND_ADDRESS}"
      - "JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "UPLOAD_DIR=${UPLOAD_DIR}"
      - "TZ=${TIMEZONE}"

  frontend:
    container_name: frontend
    image: shop-frontend:v1
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - shop_net
    environment:
      - "TZ=${TIMEZONE}"

networks:
  shop_net:
    driver: bridge

volumes:
  mysql: { }
  upload_dir: { }