server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    org:
      springframework:
        web: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webapp?useUnicode=true&serverTimeZone=UTC
    username: user1
    password: password1
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 100
  mail:
    host: example.com
    username: username
    password: password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
app:
  uploadDir: ./data/productImages/
  cart:
    cleanup:
      expression: "0 0 3 * * *"
  mail:
    sender:
      isFakeMailService: true