server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1
  forward-headers-strategy: framework
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE}?useUnicode=true&serverTimeZone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  cache:
    jcache:
      config: classpath:ehcache.xml
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 100
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
springdoc:
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: when_authorized
app:
  uploadDir: ${UPLOAD_DIR}
  cart:
    cleanup:
      expression: "0 0 3 * * *"
  mail:
    sender:
      address: ${MAIL_SENDER_ADDRESS}
      isFakeMailService: ${MAIL_FAKE_SERVICE_ENABLED:true}
  payment:
    p24:
      testMode: ${P24_TEST_MODE:true}
      merchantId: ${P24_MERCHANT_ID}
      posId: ${P24_POS_ID}
      url: https://secure.przelewy24.pl
      testUrl: https://sandbox.przelewy24.pl
      apiUrl: https://secure.przelewy24.pl/api/v1
      testApiUrl: https://sandbox.przelewy24.pl/api/v1
      urlReturn: ${P24_URL_RETURN}
      urlStatus: ${P24_URL_STATUS}
      crc: ${P24_CRC}
      testCrc: ${P24_TEST_CRC}
      secretId: ${P24_SECRET_ID}
      testSecretId: ${P24_TEST_SECRET_ID}
      servers[0]: 91.216.191.181
      servers[1]: 91.216.191.182
      servers[2]: 91.216.191.183
      servers[3]: 91.216.191.184
      servers[4]: 91.216.191.185
      servers[5]: 5.252.202.255
      servers[6]: 5.252.202.254
  serviceAddress: ${FRONTEND_ADDRESS:http://localhost:4200}
jwt:
  expirationTime: ${JWT_EXPIRATION_TIME}
  secret: ${JWT_SECRET}