logging:
  level:
    org:
      springframework:
        web: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webapp?useUnicode=true&serverTimeZone=UTC
    username: user1
    password: password1
    driverClassName: com.mysql.cj.jdbc.Driver
  liquibase:
    change-log: classpath:liquibase-changelog.xml