server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api/v1
  forward-headers-strategy: framework
logging:
  level:
    org:
      springframework:
        web: INFO
        security: INFO
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/webapp?useUnicode=true&serverTimeZone=UTC
    username: user1
    password: password1
    driverClassName: com.mysql.cj.jdbc.Driver
  cache:
    jcache:
      config: classpath:ehcache.xml
  liquibase:
    change-log: classpath:liquibase-changelog.xml
  jpa:
    show-sql: true
  data:
    web:
      pageable:
        default-page-size: 25
        max-page-size: 100
  mail:
    host: example.com
    username: username
    password: password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          port: 25
          auth: true
          starttls:
            enable: true
            required: true
springdoc:
  api-docs:
    enabled: false
    path: /api-docs
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
app:
  uploadDir: ./data/productImages/
  cart:
    cleanup:
      expression: "0 0 3 * * *"
  mail:
    sender:
      address: shop
      isFakeMailService: true
  payment:
    p24:
      testMode: true
      merchantId: 0
      posId: 0
      url: https://secure.przelewy24.pl
      testUrl: https://sandbox.przelewy24.pl
      apiUrl: https://secure.przelewy24.pl/api/v1
      testApiUrl: https://sandbox.przelewy24.pl/api/v1
      urlReturn: https://17fd-46-238-248-11.ngrok-free.app
      urlStatus: https://7df2-46-238-248-11.ngrok-free.app
      crc: crc
      testCrc: testCrc
      secretId: secretId
      testSecretId: testSecretId
      servers[0]: 91.216.191.181
      servers[1]: 91.216.191.182
      servers[2]: 91.216.191.183
      servers[3]: 91.216.191.184
      servers[4]: 91.216.191.185
      servers[5]: 5.252.202.255
      servers[6]: 5.252.202.254
  serviceAddress: http://localhost:4200
jwt:
  expirationTime: 2592000000
  secret: secret